image: Visual Studio 2022

version: 2.0.0-ci000{build}
configuration: Release
cache: C:\Users\appveyor\.nuget\packages

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build_script:
- ps: .\build.ps1

artifacts:
- path: build\nuget\*.nupkg
  name: NuGet

skip_commits:
    files:
        - tools
        - tools/
        - '.git'
        - '.git/'
        - '.github'
        - '.github/*'
        - '.github/**/*'
        - '.github/**/**/*'
        - '**/*.md'
        - 'README.md'
        - 'LICENSE*'
        - 'LICENSE*'
        - '.idea/**'
        - '.vscode/**'
        - '.gitignore'
        - 'how_to_build.txt'

test: off
