name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/FUNDING.YML'
      - '.github/dependabot.yml'
      - '.github/*.md'
      - '**/*.md'
      - '.gitconfig'
      - '.gitignore'
      - '.npmignore'
      - '*LICENSE*.*'
      - 'LICENSE'
      - '.idea/**'
      - '.vscode/**'
      - 'README.md'
      - 'appveyor.yml'
      - 'how_to_build.txt'

jobs:
  test:
    runs-on: windows-2022
    name: test-windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'

      - name: "Cake"
        shell: pwsh
        run: .\build.ps1

      - name: Upload nuget packages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: build/nuget/*.nupkg

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: test/*.Tests\TestResults\TestResults*.xml
#
#      - name: Run codacy-coverage-reporter
#        uses: codacy/codacy-coverage-reporter-action@v1.3.0
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          coverage-reports: coverage/lcov.info

  publish-test-summary:
    name: "publish test-summary"
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: publish test-summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_run_annotations: 'none'
          check_name: 'test-results'
          files: "artifacts/**/*.xml"
